#include "assembler_util.h"

std::unordered_map<std::string, lib8085::OpcodeData> lib8085::AssemblerUtil::get_instraction_str_data_map()
{
    std::unordered_map<std::string, lib8085::OpcodeData> data = {
        { "ACI", 	 lib8085::OpcodeData { "", lib8085::InstructionSet::ACI, 1, 1 } },
        { "ADC_A", 	 lib8085::OpcodeData { "", InstructionSet::ADC_A, 	0, 	1 } },
        { "ADC_B", 	 lib8085::OpcodeData { "", InstructionSet::ADC_B, 	0, 	1 } },
        { "ADC_C", 	 lib8085::OpcodeData { "", InstructionSet::ADC_C, 	0, 	1 } },
        { "ADC_D", 	 lib8085::OpcodeData { "", InstructionSet::ADC_D, 	0, 	1 } },
        { "ADC_E", 	 lib8085::OpcodeData { "", InstructionSet::ADC_E, 	0, 	1 } },
        { "ADC_H", 	 lib8085::OpcodeData { "", InstructionSet::ADC_H, 	0, 	1 } },
        { "ADC_L", 	 lib8085::OpcodeData { "", InstructionSet::ADC_L, 	0, 	1 } },
        { "ADC_M", 	 lib8085::OpcodeData { "", InstructionSet::ADC_M, 	0, 	1 } },
        { "ADD_A", 	 lib8085::OpcodeData { "", InstructionSet::ADD_A, 	0, 	1 } },
        { "ADD_B", 	 lib8085::OpcodeData { "", InstructionSet::ADD_B, 	0, 	1 } },
        { "ADD_C", 	 lib8085::OpcodeData { "", InstructionSet::ADD_C, 	0, 	1 } },
        { "ADD_D", 	 lib8085::OpcodeData { "", InstructionSet::ADD_D, 	0, 	1 } },
        { "ADD_E", 	 lib8085::OpcodeData { "", InstructionSet::ADD_E, 	0, 	1 } },
        { "ADD_H", 	 lib8085::OpcodeData { "", InstructionSet::ADD_H, 	0, 	1 } },
        { "ADD_L", 	 lib8085::OpcodeData { "", InstructionSet::ADD_L, 	0, 	1 } },
        { "ADD_M", 	 lib8085::OpcodeData { "", InstructionSet::ADD_M, 	0, 	1 } },
        { "ADI", 	 lib8085::OpcodeData { "", InstructionSet::ADI, 	1, 	1 } },
        { "ANA_A", 	 lib8085::OpcodeData { "", InstructionSet::ANA_A, 	0, 	1 } },
        { "ANA_B", 	 lib8085::OpcodeData { "", InstructionSet::ANA_B, 	0, 	1 } },
        { "ANA_C", 	 lib8085::OpcodeData { "", InstructionSet::ANA_C, 	0, 	1 } },
        { "ANA_D", 	 lib8085::OpcodeData { "", InstructionSet::ANA_D, 	0, 	1 } },
        { "ANA_E", 	 lib8085::OpcodeData { "", InstructionSet::ANA_E, 	0, 	1 } },
        { "ANA_H", 	 lib8085::OpcodeData { "", InstructionSet::ANA_H, 	0, 	1 } },
        { "ANA_L", 	 lib8085::OpcodeData { "", InstructionSet::ANA_L, 	0, 	1 } },
        { "ANA_M", 	 lib8085::OpcodeData { "", InstructionSet::ANA_M, 	0, 	1 } },
        { "ANI", 	 lib8085::OpcodeData { "", InstructionSet::ANI, 	1, 	1 } },
        { "CALL", 	 lib8085::OpcodeData { "", InstructionSet::CALL, 	1, 	2 } },
        { "CC", 	 lib8085::OpcodeData { "", InstructionSet::CC, 	1, 	2 } },
        { "CM", 	 lib8085::OpcodeData { "", InstructionSet::CM, 	1, 	2 } },
        { "CMA", 	 lib8085::OpcodeData { "", InstructionSet::CMA, 	0, 	1 } },
        { "CMC", 	 lib8085::OpcodeData { "", InstructionSet::CMC, 	0, 	1 } },
        { "CMP_A", 	 lib8085::OpcodeData { "", InstructionSet::CMP_A, 	0, 	1 } },
        { "CMP_B", 	 lib8085::OpcodeData { "", InstructionSet::CMP_B, 	0, 	1 } },
        { "CMP_C", 	 lib8085::OpcodeData { "", InstructionSet::CMP_C, 	0, 	1 } },
        { "CMP_D", 	 lib8085::OpcodeData { "", InstructionSet::CMP_D, 	0, 	1 } },
        { "CMP_E", 	 lib8085::OpcodeData { "", InstructionSet::CMP_E, 	0, 	1 } },
        { "CMP_H", 	 lib8085::OpcodeData { "", InstructionSet::CMP_H, 	0, 	1 } },
        { "CMP_L", 	 lib8085::OpcodeData { "", InstructionSet::CMP_L, 	0, 	1 } },
        { "CMP_M", 	 lib8085::OpcodeData { "", InstructionSet::CMP_M, 	0, 	1 } },
        { "CNC", 	 lib8085::OpcodeData { "", InstructionSet::CNC, 	1, 	2 } },
        { "CNZ", 	 lib8085::OpcodeData { "", InstructionSet::CNZ, 	1, 	2 } },
        { "CP", 	 lib8085::OpcodeData { "", InstructionSet::CP, 	1, 	2 } },
        { "CPE", 	 lib8085::OpcodeData { "", InstructionSet::CPE, 	1, 	2 } },
        { "CPI", 	 lib8085::OpcodeData { "", InstructionSet::CPI, 	1, 	1 } },
        { "CPO", 	 lib8085::OpcodeData { "", InstructionSet::CPO, 	1, 	2 } },
        { "CZ", 	 lib8085::OpcodeData { "", InstructionSet::CZ, 	1, 	1 } },
        { "DAA", 	 lib8085::OpcodeData { "", InstructionSet::DAA, 	0, 	1 } },
        { "DAD_B", 	 lib8085::OpcodeData { "", InstructionSet::DAD_B, 	0, 	1 } },
        { "DAD_D", 	 lib8085::OpcodeData { "", InstructionSet::DAD_D, 	0, 	1 } },
        { "DAD_H", 	 lib8085::OpcodeData { "", InstructionSet::DAD_H, 	0, 	1 } },
        { "DAD_SP",  lib8085::OpcodeData { "", InstructionSet::DAD_SP,	0, 	1 } },
        { "DCR_A", 	 lib8085::OpcodeData { "", InstructionSet::DCR_A, 	0, 	1 } },
        { "DCR_B", 	 lib8085::OpcodeData { "", InstructionSet::DCR_B, 	0, 	1 } },
        { "DCR_C", 	 lib8085::OpcodeData { "", InstructionSet::DCR_C, 	0, 	1 } },
        { "DCR_D", 	 lib8085::OpcodeData { "", InstructionSet::DCR_D, 	0, 	1 } },
        { "DCR_E", 	 lib8085::OpcodeData { "", InstructionSet::DCR_E, 	0, 	1 } },
        { "DCR_H", 	 lib8085::OpcodeData { "", InstructionSet::DCR_H, 	0, 	1 } },
        { "DCR_L", 	 lib8085::OpcodeData { "", InstructionSet::DCR_L, 	0, 	1 } },
        { "DCR_M", 	 lib8085::OpcodeData { "", InstructionSet::DCR_M, 	0, 	1 } },
        { "DCX_B", 	 lib8085::OpcodeData { "", InstructionSet::DCX_B, 	0, 	1 } },
        { "DCX_D", 	 lib8085::OpcodeData { "", InstructionSet::DCX_D, 	0, 	1 } },
        { "DCX_H", 	 lib8085::OpcodeData { "", InstructionSet::DCX_H, 	0, 	1 } },
        { "DCX_SP",  lib8085::OpcodeData { "", InstructionSet::DCX_SP,	0, 	1 } },
        { "DI", 	 lib8085::OpcodeData { "", InstructionSet::DI, 	0, 	1 } },
        { "EI", 	 lib8085::OpcodeData { "", InstructionSet::EI, 	0, 	1 } },
        { "HLT", 	 lib8085::OpcodeData { "", InstructionSet::HLT, 	0, 	1 } },
        { "IN", 	 lib8085::OpcodeData { "", InstructionSet::IN, 	1, 	1 } },
        { "INR_A", 	 lib8085::OpcodeData { "", InstructionSet::INR_A, 	0, 	1 } },
        { "INR_B", 	 lib8085::OpcodeData { "", InstructionSet::INR_B, 	0, 	1 } },
        { "INR_C", 	 lib8085::OpcodeData { "", InstructionSet::INR_C, 	0, 	1 } },
        { "INR_D", 	 lib8085::OpcodeData { "", InstructionSet::INR_D, 	0, 	1 } },
        { "INR_E", 	 lib8085::OpcodeData { "", InstructionSet::INR_E, 	0, 	1 } },
        { "INR_H", 	 lib8085::OpcodeData { "", InstructionSet::INR_H, 	0, 	1 } },
        { "INR_L", 	 lib8085::OpcodeData { "", InstructionSet::INR_L, 	0, 	1 } },
        { "INR_M", 	 lib8085::OpcodeData { "", InstructionSet::INR_M, 	0, 	1 } },
        { "INX_B", 	 lib8085::OpcodeData { "", InstructionSet::INX_B, 	0, 	1 } },
        { "INX_D", 	 lib8085::OpcodeData { "", InstructionSet::INX_D, 	0, 	1 } },
        { "INX_H", 	 lib8085::OpcodeData { "", InstructionSet::INX_H, 	0, 	1 } },
        { "INX_SP",  lib8085::OpcodeData { "", InstructionSet::INX_SP,	0, 	1 } },
        { "JC", 	 lib8085::OpcodeData { "", InstructionSet::JC, 	1, 	2 } },
        { "JM", 	 lib8085::OpcodeData { "", InstructionSet::JM, 	1, 	2 } },
        { "JMP", 	 lib8085::OpcodeData { "", InstructionSet::JMP, 	1, 	2 } },
        { "JNC", 	 lib8085::OpcodeData { "", InstructionSet::JNC, 	1, 	2 } },
        { "JNZ", 	 lib8085::OpcodeData { "", InstructionSet::JNZ, 	1, 	2 } },
        { "JP", 	 lib8085::OpcodeData { "", InstructionSet::JP, 	1, 	2 } },
        { "JPE", 	 lib8085::OpcodeData { "", InstructionSet::JPE, 	1, 	2 } },
        { "JPO", 	 lib8085::OpcodeData { "", InstructionSet::JPO, 	1, 	2 } },
        { "JZ", 	 lib8085::OpcodeData { "", InstructionSet::JZ, 	1, 	2 } },
        { "LDA", 	 lib8085::OpcodeData { "", InstructionSet::LDA, 	1, 	2 } },
        { "LDAX_B",  lib8085::OpcodeData { "", InstructionSet::LDAX_B,	0, 	1 } },
        { "LDAX_D",  lib8085::OpcodeData { "", InstructionSet::LDAX_D,	0, 	1 } },
        { "LHLD", 	 lib8085::OpcodeData { "", InstructionSet::LHLD, 	1, 	2 } },
        { "LXI_B", 	 lib8085::OpcodeData { "", InstructionSet::LXI_B, 	1, 	2 } },
        { "LXI_D", 	 lib8085::OpcodeData { "", InstructionSet::LXI_D, 	1, 	2 } },
        { "LXI_H", 	 lib8085::OpcodeData { "", InstructionSet::LXI_H, 	1, 	2 } },
        { "LXI_SP",  lib8085::OpcodeData { "", InstructionSet::LXI_SP,	1, 	2 } },
        { "MOV_A_A", lib8085::OpcodeData { "", InstructionSet::MOV_A_A , 0, 	1 } },
        { "MOV_A_B", lib8085::OpcodeData { "", InstructionSet::MOV_A_B , 0, 	1 } },
        { "MOV_A_C", lib8085::OpcodeData { "", InstructionSet::MOV_A_C , 0, 	1 } },
        { "MOV_A_D", lib8085::OpcodeData { "", InstructionSet::MOV_A_D , 0, 	1 } },
        { "MOV_A_E", lib8085::OpcodeData { "", InstructionSet::MOV_A_E , 0, 	1 } },
        { "MOV_A_H", lib8085::OpcodeData { "", InstructionSet::MOV_A_H , 0, 	1 } },
        { "MOV_A_L", lib8085::OpcodeData { "", InstructionSet::MOV_A_L , 0, 	1 } },
        { "MOV_A_M", lib8085::OpcodeData { "", InstructionSet::MOV_A_M , 0, 	1 } },
        { "MOV_B_A", lib8085::OpcodeData { "", InstructionSet::MOV_B_A , 0, 	1 } },
        { "MOV_B_B", lib8085::OpcodeData { "", InstructionSet::MOV_B_B , 0, 	1 } },
        { "MOV_B_C", lib8085::OpcodeData { "", InstructionSet::MOV_B_C , 0, 	1 } },
        { "MOV_B_D", lib8085::OpcodeData { "", InstructionSet::MOV_B_D , 0, 	1 } },
        { "MOV_B_E", lib8085::OpcodeData { "", InstructionSet::MOV_B_E , 0, 	1 } },
        { "MOV_B_H", lib8085::OpcodeData { "", InstructionSet::MOV_B_H , 0, 	1 } },
        { "MOV_B_L", lib8085::OpcodeData { "", InstructionSet::MOV_B_L , 0, 	1 } },
        { "MOV_B_M", lib8085::OpcodeData { "", InstructionSet::MOV_B_M , 0, 	1 } },
        { "MOV_C_A", lib8085::OpcodeData { "", InstructionSet::MOV_C_A , 0, 	1 } },
        { "MOV_C_B", lib8085::OpcodeData { "", InstructionSet::MOV_C_B , 0, 	1 } },
        { "MOV_C_C", lib8085::OpcodeData { "", InstructionSet::MOV_C_C , 0, 	1 } },
        { "MOV_C_D", lib8085::OpcodeData { "", InstructionSet::MOV_C_D , 0, 	1 } },
        { "MOV_C_E", lib8085::OpcodeData { "", InstructionSet::MOV_C_E , 0, 	1 } },
        { "MOV_C_H", lib8085::OpcodeData { "", InstructionSet::MOV_C_H , 0, 	1 } },
        { "MOV_C_L", lib8085::OpcodeData { "", InstructionSet::MOV_C_L , 0, 	1 } },
        { "MOV_C_M", lib8085::OpcodeData { "", InstructionSet::MOV_C_M , 0, 	1 } },
        { "MOV_D_A", lib8085::OpcodeData { "", InstructionSet::MOV_D_A , 0, 	1 } },
        { "MOV_D_B", lib8085::OpcodeData { "", InstructionSet::MOV_D_B , 0, 	1 } },
        { "MOV_D_C", lib8085::OpcodeData { "", InstructionSet::MOV_D_C , 0, 	1 } },
        { "MOV_D_D", lib8085::OpcodeData { "", InstructionSet::MOV_D_D , 0, 	1 } },
        { "MOV_D_E", lib8085::OpcodeData { "", InstructionSet::MOV_D_E , 0, 	1 } },
        { "MOV_D_H", lib8085::OpcodeData { "", InstructionSet::MOV_D_H , 0, 	1 } },
        { "MOV_D_L", lib8085::OpcodeData { "", InstructionSet::MOV_D_L , 0, 	1 } },
        { "MOV_D_M", lib8085::OpcodeData { "", InstructionSet::MOV_E_A , 0, 	2 } },
        { "MOV_E_A", lib8085::OpcodeData { "", InstructionSet::MOV_E_A , 0, 	1 } },
        { "MOV_E_B", lib8085::OpcodeData { "", InstructionSet::MOV_E_B , 0, 	1 } },
        { "MOV_E_C", lib8085::OpcodeData { "", InstructionSet::MOV_E_C , 0, 	1 } },
        { "MOV_E_D", lib8085::OpcodeData { "", InstructionSet::MOV_E_D , 0, 	1 } },
        { "MOV_E_E", lib8085::OpcodeData { "", InstructionSet::MOV_E_E , 0, 	1 } },
        { "MOV_E_H", lib8085::OpcodeData { "", InstructionSet::MOV_E_H , 0, 	1 } },
        { "MOV_E_L", lib8085::OpcodeData { "", InstructionSet::MOV_E_L , 0, 	1 } },
        { "MOV_E_M", lib8085::OpcodeData { "", InstructionSet::MOV_E_M , 0, 	1 } },
        { "MOV_H_A", lib8085::OpcodeData { "", InstructionSet::MOV_H_A , 0, 	1 } },
        { "MOV_H_B", lib8085::OpcodeData { "", InstructionSet::MOV_H_B , 0, 	1 } },
        { "MOV_H_C", lib8085::OpcodeData { "", InstructionSet::MOV_H_C , 0, 	1 } },
        { "MOV_H_D", lib8085::OpcodeData { "", InstructionSet::MOV_H_D , 0, 	1 } },
        { "MOV_H_E", lib8085::OpcodeData { "", InstructionSet::MOV_H_E , 0, 	1 } },
        { "MOV_H_H", lib8085::OpcodeData { "", InstructionSet::MOV_H_H , 0, 	1 } },
        { "MOV_H_L", lib8085::OpcodeData { "", InstructionSet::MOV_H_L , 0, 	1 } },
        { "MOV_H_M", lib8085::OpcodeData { "", InstructionSet::MOV_H_M , 0, 	1 } },
        { "MOV_L_A", lib8085::OpcodeData { "", InstructionSet::MOV_L_A , 0, 	1 } },
        { "MOV_L_B", lib8085::OpcodeData { "", InstructionSet::MOV_L_B , 0, 	1 } },
        { "MOV_L_C", lib8085::OpcodeData { "", InstructionSet::MOV_L_C , 0, 	1 } },
        { "MOV_L_D", lib8085::OpcodeData { "", InstructionSet::MOV_L_D , 0, 	1 } },
        { "MOV_L_E", lib8085::OpcodeData { "", InstructionSet::MOV_L_E , 0, 	1 } },
        { "MOV_L_H", lib8085::OpcodeData { "", InstructionSet::MOV_L_H , 0, 	1 } },
        { "MOV_L_L", lib8085::OpcodeData { "", InstructionSet::MOV_L_L , 0, 	1 } },
        { "MOV_L_M", lib8085::OpcodeData { "", InstructionSet::MOV_L_M , 0, 	1 } },
        { "MOV_M_A", lib8085::OpcodeData { "", InstructionSet::MOV_M_A , 0, 	1 } },
        { "MOV_M_B", lib8085::OpcodeData { "", InstructionSet::MOV_M_B , 0, 	1 } },
        { "MOV_M_C", lib8085::OpcodeData { "", InstructionSet::MOV_M_C , 0, 	1 } },
        { "MOV_M_D", lib8085::OpcodeData { "", InstructionSet::MOV_M_D , 0, 	1 } },
        { "MOV_M_E", lib8085::OpcodeData { "", InstructionSet::MOV_M_E , 0, 	1 } },
        { "MOV_M_H", lib8085::OpcodeData { "", InstructionSet::MOV_M_H , 0, 	1 } },
        { "MOV_M_L", lib8085::OpcodeData { "", InstructionSet::MOV_M_L , 0, 	1 } },
        { "MVI_A", 	 lib8085::OpcodeData { "", InstructionSet::MVI_A, 	1, 	1 } },
        { "MVI_B", 	 lib8085::OpcodeData { "", InstructionSet::MVI_B, 	1, 	1 } },
        { "MVI_C", 	 lib8085::OpcodeData { "", InstructionSet::MVI_C, 	1, 	1 } },
        { "MVI_D", 	 lib8085::OpcodeData { "", InstructionSet::MVI_D, 	1, 	1 } },
        { "MVI_E", 	 lib8085::OpcodeData { "", InstructionSet::MVI_E, 	1, 	1 } },
        { "MVI_H", 	 lib8085::OpcodeData { "", InstructionSet::MVI_H, 	1, 	1 } },
        { "MVI_L", 	 lib8085::OpcodeData { "", InstructionSet::MVI_L, 	1, 	1 } },
        { "MVI_M", 	 lib8085::OpcodeData { "", InstructionSet::MVI_M, 	1, 	1 } },
        { "NOP", 	 lib8085::OpcodeData { "", InstructionSet::NOP, 	0, 	1 } },
        { "ORA_A", 	 lib8085::OpcodeData { "", InstructionSet::ORA_A, 	0, 	1 } },
        { "ORA_B", 	 lib8085::OpcodeData { "", InstructionSet::ORA_B, 	0, 	1 } },
        { "ORA_C", 	 lib8085::OpcodeData { "", InstructionSet::ORA_C, 	0, 	1 } },
        { "ORA_D", 	 lib8085::OpcodeData { "", InstructionSet::ORA_D, 	0, 	1 } },
        { "ORA_E", 	 lib8085::OpcodeData { "", InstructionSet::ORA_E, 	0, 	1 } },
        { "ORA_H", 	 lib8085::OpcodeData { "", InstructionSet::ORA_H, 	0, 	1 } },
        { "ORA_L", 	 lib8085::OpcodeData { "", InstructionSet::ORA_L, 	0, 	1 } },
        { "ORA_M", 	 lib8085::OpcodeData { "", InstructionSet::ORA_M, 	0, 	1 } },
        { "ORI", 	 lib8085::OpcodeData { "", InstructionSet::ORI, 	1, 	1 } },
        { "OUT", 	 lib8085::OpcodeData { "", InstructionSet::OUT, 	1, 	1 } },
        { "PCHL", 	 lib8085::OpcodeData { "", InstructionSet::PCHL, 	0, 	1 } },
        { "POP_B", 	 lib8085::OpcodeData { "", InstructionSet::POP_B, 	0, 	1 } },
        { "POP_D", 	 lib8085::OpcodeData { "", InstructionSet::POP_D, 	0, 	1 } },
        { "POP_H", 	 lib8085::OpcodeData { "", InstructionSet::POP_H, 	0, 	1 } },
        { "POP_PSW", lib8085::OpcodeData { "", InstructionSet::POP_PSW , 0, 	1 } },
        { "PUSH_B",  lib8085::OpcodeData { "", InstructionSet::PUSH_B , 0, 	1 } },
        { "PUSH_D",  lib8085::OpcodeData { "", InstructionSet::PUSH_D , 0, 	1 } },
        { "PUSH_H",  lib8085::OpcodeData { "", InstructionSet::PUSH_H , 0, 	1 } },
        { "PUSH_PSW",lib8085::OpcodeData { "", InstructionSet::PUSH_PSW, 0,  1 } },
        { "RAL", 	 lib8085::OpcodeData { "", InstructionSet::RAL, 	0, 	1 } },
        { "RAR", 	 lib8085::OpcodeData { "", InstructionSet::RAR, 	0, 	1 } },
        { "RC", 	 lib8085::OpcodeData { "", InstructionSet::RC, 	0, 	1 } },
        { "RET", 	 lib8085::OpcodeData { "", InstructionSet::RET, 	0, 	1 } },
        { "RIM", 	 lib8085::OpcodeData { "", InstructionSet::RIM, 	0, 	1 } },
        { "RLC", 	 lib8085::OpcodeData { "", InstructionSet::RLC, 	0, 	1 } },
        { "RM", 	 lib8085::OpcodeData { "", InstructionSet::RM, 	0, 	1 } },
        { "RNC", 	 lib8085::OpcodeData { "", InstructionSet::RNC, 	0, 	1 } },
        { "RNZ", 	 lib8085::OpcodeData { "", InstructionSet::RNZ, 	0, 	1 } },
        { "RP", 	 lib8085::OpcodeData { "", InstructionSet::RP, 	0, 	1 } },
        { "RPE", 	 lib8085::OpcodeData { "", InstructionSet::RPE, 	0, 	1 } },
        { "RPO", 	 lib8085::OpcodeData { "", InstructionSet::RPO, 	0, 	1 } },
        { "RRC", 	 lib8085::OpcodeData { "", InstructionSet::RRC, 	0, 	1 } },
        { "RST_0", 	 lib8085::OpcodeData { "", InstructionSet::RST_0, 	1, 	2 } },
        { "RST_1", 	 lib8085::OpcodeData { "", InstructionSet::RST_1, 	1, 	2 } },
        { "RST_2", 	 lib8085::OpcodeData { "", InstructionSet::RST_2, 	1, 	2 } },
        { "RST_3", 	 lib8085::OpcodeData { "", InstructionSet::RST_3, 	1, 	2 } },
        { "RST_4", 	 lib8085::OpcodeData { "", InstructionSet::RST_4, 	1, 	2 } },
        { "RST_5", 	 lib8085::OpcodeData { "", InstructionSet::RST_5, 	1, 	2 } },
        { "RST_6", 	 lib8085::OpcodeData { "", InstructionSet::RST_6, 	1, 	2 } },
        { "RST_7", 	 lib8085::OpcodeData { "", InstructionSet::RST_7, 	1, 	2 } },
        { "RZ", 	 lib8085::OpcodeData { "", InstructionSet::RZ, 	0, 	1 } },
        { "SBB_A", 	 lib8085::OpcodeData { "", InstructionSet::SBB_A, 	0, 	1 } },
        { "SBB_B", 	 lib8085::OpcodeData { "", InstructionSet::SBB_B, 	0, 	1 } },
        { "SBB_C", 	 lib8085::OpcodeData { "", InstructionSet::SBB_C, 	0, 	1 } },
        { "SBB_D", 	 lib8085::OpcodeData { "", InstructionSet::SBB_D, 	0, 	1 } },
        { "SBB_E", 	 lib8085::OpcodeData { "", InstructionSet::SBB_E, 	0, 	1 } },
        { "SBB_H", 	 lib8085::OpcodeData { "", InstructionSet::SBB_H, 	0, 	1 } },
        { "SBB_L", 	 lib8085::OpcodeData { "", InstructionSet::SBB_L, 	0, 	1 } },
        { "SBB_M", 	 lib8085::OpcodeData { "", InstructionSet::SBB_M, 	0, 	1 } },
        { "SBI", 	 lib8085::OpcodeData { "", InstructionSet::SBI, 	1, 	1 } },
        { "SHLD", 	 lib8085::OpcodeData { "", InstructionSet::SHLD, 	1, 	2 } },
        { "SIM", 	 lib8085::OpcodeData { "", InstructionSet::SIM, 	0, 	1 } },
        { "SPHL", 	 lib8085::OpcodeData { "", InstructionSet::SPHL, 	0, 	1 } },
        { "STA", 	 lib8085::OpcodeData { "", InstructionSet::STA, 	1, 	2 } },
        { "STAX_B",  lib8085::OpcodeData { "", InstructionSet::STAX_B, 0, 	1 } },
        { "STAX_D",  lib8085::OpcodeData { "", InstructionSet::STAX_D, 0, 	1 } },
        { "STAX_H",  lib8085::OpcodeData { "", InstructionSet::STAX_H, 0, 	1 } },
        { "STC", 	 lib8085::OpcodeData { "", InstructionSet::STC, 	0, 	1 } },
        { "SUB_A", 	 lib8085::OpcodeData { "", InstructionSet::SUB_A, 	0, 	1 } },
        { "SUB_B", 	 lib8085::OpcodeData { "", InstructionSet::SUB_B, 	0, 	1 } },
        { "SUB_C", 	 lib8085::OpcodeData { "", InstructionSet::SUB_C, 	0, 	1 } },
        { "SUB_D", 	 lib8085::OpcodeData { "", InstructionSet::SUB_D, 	0, 	1 } },
        { "SUB_E", 	 lib8085::OpcodeData { "", InstructionSet::SUB_E, 	0, 	1 } },
        { "SUB_H", 	 lib8085::OpcodeData { "", InstructionSet::SUB_H, 	0, 	1 } },
        { "SUB_L", 	 lib8085::OpcodeData { "", InstructionSet::SUB_L, 	0, 	1 } },
        { "SUB_M", 	 lib8085::OpcodeData { "", InstructionSet::SUB_M, 	0, 	1 } },
        { "SUI", 	 lib8085::OpcodeData { "", InstructionSet::SUI, 	1, 	1 } },
        { "XCHG", 	 lib8085::OpcodeData { "", InstructionSet::XCHG, 	0, 	1 } },
        { "XRA_A", 	 lib8085::OpcodeData { "", InstructionSet::XRA_A, 	0, 	1 } },
        { "XRA_B", 	 lib8085::OpcodeData { "", InstructionSet::XRA_B, 	0, 	1 } },
        { "XRA_C", 	 lib8085::OpcodeData { "", InstructionSet::XRA_C, 	0, 	1 } },
        { "XRA_D", 	 lib8085::OpcodeData { "", InstructionSet::XRA_D, 	0, 	1 } },
        { "XRA_E", 	 lib8085::OpcodeData { "", InstructionSet::XRA_E, 	0, 	1 } },
        { "XRA_H", 	 lib8085::OpcodeData { "", InstructionSet::XRA_H, 	0, 	1 } },
        { "XRA_L", 	 lib8085::OpcodeData { "", InstructionSet::XRA_L, 	0, 	1 } },
        { "XRA_M", 	 lib8085::OpcodeData { "", InstructionSet::XRA_M, 	0, 	1 } },
        { "XRI", 	 lib8085::OpcodeData { "", InstructionSet::XRI, 	1, 	1 } },
        { "XTHL", 	 lib8085::OpcodeData { "", InstructionSet::XTHL, 	0, 	1 } }
    };

    return data;
}


std::unordered_map<lib8085::InstructionSet, lib8085::OpcodeData> lib8085::AssemblerUtil::get_instraction_data_map()
{
    std::unordered_map<lib8085::InstructionSet, lib8085::OpcodeData> data = {
        { lib8085::InstructionSet::ACI,    lib8085::OpcodeData { "ACI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::ADC_A,  lib8085::OpcodeData { "ADC_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_B,  lib8085::OpcodeData { "ADC_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_C,  lib8085::OpcodeData { "ADC_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_D,  lib8085::OpcodeData { "ADC_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_E,  lib8085::OpcodeData { "ADC_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_H,  lib8085::OpcodeData { "ADC_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_L,  lib8085::OpcodeData { "ADC_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADC_M,  lib8085::OpcodeData { "ADC_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_A,  lib8085::OpcodeData { "ADD_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_B,  lib8085::OpcodeData { "ADD_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_C,  lib8085::OpcodeData { "ADD_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_D,  lib8085::OpcodeData { "ADD_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_E,  lib8085::OpcodeData { "ADD_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_H,  lib8085::OpcodeData { "ADD_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_L,  lib8085::OpcodeData { "ADD_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADD_M,  lib8085::OpcodeData { "ADD_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ADI,    lib8085::OpcodeData { "ADI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::ANA_A,  lib8085::OpcodeData { "ANA_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_B,  lib8085::OpcodeData { "ANA_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_C,  lib8085::OpcodeData { "ANA_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_D,  lib8085::OpcodeData { "ANA_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_E,  lib8085::OpcodeData { "ANA_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_H,  lib8085::OpcodeData { "ANA_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_L,  lib8085::OpcodeData { "ANA_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANA_M,  lib8085::OpcodeData { "ANA_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ANI,    lib8085::OpcodeData { "ANI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::CALL,   lib8085::OpcodeData { "CALL", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::CC,     lib8085::OpcodeData { "CC", InstructionSet::NOP, 	    1, 	2 } },
        { lib8085::InstructionSet::CM,     lib8085::OpcodeData { "CM", InstructionSet::NOP,      1, 	2 } },
        { lib8085::InstructionSet::CMA,    lib8085::OpcodeData { "CMA", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMC,    lib8085::OpcodeData { "CMC", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_A,  lib8085::OpcodeData { "CMP_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_B,  lib8085::OpcodeData { "CMP_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_C,  lib8085::OpcodeData { "CMP_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_D,  lib8085::OpcodeData { "CMP_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_E,  lib8085::OpcodeData { "CMP_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_H,  lib8085::OpcodeData { "CMP_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_L,  lib8085::OpcodeData { "CMP_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CMP_M,  lib8085::OpcodeData { "CMP_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::CNC,    lib8085::OpcodeData { "CNC", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::CNZ,    lib8085::OpcodeData { "CNZ", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::CP,     lib8085::OpcodeData { "CP", InstructionSet::NOP,	    1, 	2 } },
        { lib8085::InstructionSet::CPE,    lib8085::OpcodeData { "CPE", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::CPI,    lib8085::OpcodeData { "CPI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::CPO,    lib8085::OpcodeData { "CPO", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::CZ,     lib8085::OpcodeData { "CZ", InstructionSet::NOP, 	    1, 	1 } },
        { lib8085::InstructionSet::DAA,    lib8085::OpcodeData { "DAA", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DAD_B,  lib8085::OpcodeData { "DAD_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DAD_D,  lib8085::OpcodeData { "DAD_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DAD_H,  lib8085::OpcodeData { "DAD_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DAD_SP, lib8085::OpcodeData { "DAD_SP", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_A,  lib8085::OpcodeData { "DCR_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_B,  lib8085::OpcodeData { "DCR_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_C,  lib8085::OpcodeData { "DCR_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_D,  lib8085::OpcodeData { "DCR_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_E,  lib8085::OpcodeData { "DCR_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_H,  lib8085::OpcodeData { "DCR_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_L,  lib8085::OpcodeData { "DCR_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCR_M,  lib8085::OpcodeData { "DCR_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCX_B,  lib8085::OpcodeData { "DCX_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCX_D,  lib8085::OpcodeData { "DCX_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCX_H,  lib8085::OpcodeData { "DCX_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DCX_SP, lib8085::OpcodeData { "DCX_SP", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::DI,     lib8085::OpcodeData { "DI", InstructionSet::NOP, 	    0, 	1 } },
        { lib8085::InstructionSet::EI,     lib8085::OpcodeData { "EI", InstructionSet::NOP,	    0, 	1 } },
        { lib8085::InstructionSet::HLT,    lib8085::OpcodeData { "HLT", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::IN,     lib8085::OpcodeData { "IN", InstructionSet::NOP, 	    1, 	1 } },
        { lib8085::InstructionSet::INR_A,  lib8085::OpcodeData { "INR_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_B,  lib8085::OpcodeData { "INR_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_C,  lib8085::OpcodeData { "INR_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_D,  lib8085::OpcodeData { "INR_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_E,  lib8085::OpcodeData { "INR_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_H,  lib8085::OpcodeData { "INR_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_L,  lib8085::OpcodeData { "INR_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INR_M,  lib8085::OpcodeData { "INR_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INX_B,  lib8085::OpcodeData { "INX_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INX_D,  lib8085::OpcodeData { "INX_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INX_H,  lib8085::OpcodeData { "INX_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::INX_SP, lib8085::OpcodeData { "INX_SP", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::JC,     lib8085::OpcodeData { "JC", InstructionSet::NOP,	    1, 	2 } },
        { lib8085::InstructionSet::JM,     lib8085::OpcodeData { "JM", InstructionSet::NOP,	    1, 	2 } },
        { lib8085::InstructionSet::JMP,    lib8085::OpcodeData { "JMP", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::JNC,    lib8085::OpcodeData { "JNC", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::JNZ,    lib8085::OpcodeData { "JNZ", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::JP,     lib8085::OpcodeData { "JP", InstructionSet::NOP, 	    1, 	2 } },
        { lib8085::InstructionSet::JPE,    lib8085::OpcodeData { "JPE", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::JPO,    lib8085::OpcodeData { "JPO", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::JZ,     lib8085::OpcodeData { "JZ", InstructionSet::NOP, 	    1, 	2 } },
        { lib8085::InstructionSet::LDA,    lib8085::OpcodeData { "LDA", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::LDAX_B, lib8085::OpcodeData { "LDAX_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::LDAX_D, lib8085::OpcodeData { "LDAX_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::LHLD,   lib8085::OpcodeData { "LHLD", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::LXI_B,  lib8085::OpcodeData { "LXI_B", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::LXI_D,  lib8085::OpcodeData { "LXI_D", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::LXI_H,  lib8085::OpcodeData { "LXI_H", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::LXI_SP, lib8085::OpcodeData { "LXI_SP", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::MOV_A_A,lib8085::OpcodeData { "MOV_A_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_B,lib8085::OpcodeData { "MOV_A_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_C,lib8085::OpcodeData { "MOV_A_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_D,lib8085::OpcodeData { "MOV_A_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_E,lib8085::OpcodeData { "MOV_A_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_H,lib8085::OpcodeData { "MOV_A_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_L,lib8085::OpcodeData { "MOV_A_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_A_M,lib8085::OpcodeData { "MOV_A_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_A,lib8085::OpcodeData { "MOV_B_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_B,lib8085::OpcodeData { "MOV_B_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_C,lib8085::OpcodeData { "MOV_B_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_D,lib8085::OpcodeData { "MOV_B_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_E,lib8085::OpcodeData { "MOV_B_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_H,lib8085::OpcodeData { "MOV_B_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_L,lib8085::OpcodeData { "MOV_B_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_B_M,lib8085::OpcodeData { "MOV_B_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_A,lib8085::OpcodeData { "MOV_C_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_B,lib8085::OpcodeData { "MOV_C_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_C,lib8085::OpcodeData { "MOV_C_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_D,lib8085::OpcodeData { "MOV_C_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_E,lib8085::OpcodeData { "MOV_C_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_H,lib8085::OpcodeData { "MOV_C_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_L,lib8085::OpcodeData { "MOV_C_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_C_M,lib8085::OpcodeData { "MOV_C_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_A,lib8085::OpcodeData { "MOV_D_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_B,lib8085::OpcodeData { "MOV_D_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_C,lib8085::OpcodeData { "MOV_D_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_D,lib8085::OpcodeData { "MOV_D_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_E,lib8085::OpcodeData { "MOV_D_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_H,lib8085::OpcodeData { "MOV_D_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_L,lib8085::OpcodeData { "MOV_D_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_D_M,lib8085::OpcodeData { "MOV_D_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_A,lib8085::OpcodeData { "MOV_E_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_B,lib8085::OpcodeData { "MOV_E_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_C,lib8085::OpcodeData { "MOV_E_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_D,lib8085::OpcodeData { "MOV_E_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_E,lib8085::OpcodeData { "MOV_E_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_H,lib8085::OpcodeData { "MOV_E_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_L,lib8085::OpcodeData { "MOV_E_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_E_M,lib8085::OpcodeData { "MOV_E_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_A,lib8085::OpcodeData { "MOV_H_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_B,lib8085::OpcodeData { "MOV_H_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_C,lib8085::OpcodeData { "MOV_H_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_D,lib8085::OpcodeData { "MOV_H_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_E,lib8085::OpcodeData { "MOV_H_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_H,lib8085::OpcodeData { "MOV_H_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_L,lib8085::OpcodeData { "MOV_H_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_H_M,lib8085::OpcodeData { "MOV_H_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_A,lib8085::OpcodeData { "MOV_L_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_B,lib8085::OpcodeData { "MOV_L_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_C,lib8085::OpcodeData { "MOV_L_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_D,lib8085::OpcodeData { "MOV_L_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_E,lib8085::OpcodeData { "MOV_L_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_H,lib8085::OpcodeData { "MOV_L_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_L,lib8085::OpcodeData { "MOV_L_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_L_M,lib8085::OpcodeData { "MOV_L_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_A,lib8085::OpcodeData { "MOV_M_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_B,lib8085::OpcodeData { "MOV_M_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_C,lib8085::OpcodeData { "MOV_M_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_D,lib8085::OpcodeData { "MOV_M_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_E,lib8085::OpcodeData { "MOV_M_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_H,lib8085::OpcodeData { "MOV_M_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MOV_M_L,lib8085::OpcodeData { "MOV_M_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::MVI_A,  lib8085::OpcodeData { "MVI_A", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_B,  lib8085::OpcodeData { "MVI_B", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_C,  lib8085::OpcodeData { "MVI_C", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_D,  lib8085::OpcodeData { "MVI_D", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_E,  lib8085::OpcodeData { "MVI_E", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_H,  lib8085::OpcodeData { "MVI_H", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_L,  lib8085::OpcodeData { "MVI_L", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::MVI_M,  lib8085::OpcodeData { "MVI_M", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::NOP,    lib8085::OpcodeData { "NOP", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_A,  lib8085::OpcodeData { "ORA_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_B,  lib8085::OpcodeData { "ORA_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_C,  lib8085::OpcodeData { "ORA_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_D,  lib8085::OpcodeData { "ORA_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_E,  lib8085::OpcodeData { "ORA_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_H,  lib8085::OpcodeData { "ORA_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_L,  lib8085::OpcodeData { "ORA_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORA_M,  lib8085::OpcodeData { "ORA_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::ORI,    lib8085::OpcodeData { "ORI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::OUT,    lib8085::OpcodeData { "OUT", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::PCHL,   lib8085::OpcodeData { "PCHL", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::POP_B,  lib8085::OpcodeData { "POP_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::POP_D,  lib8085::OpcodeData { "POP_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::POP_H,  lib8085::OpcodeData { "POP_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::POP_PSW,lib8085::OpcodeData { "POP_PSW", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::PUSH_B, lib8085::OpcodeData { "PUSH_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::PUSH_D, lib8085::OpcodeData { "PUSH_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::PUSH_H, lib8085::OpcodeData { "PUSH_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::PUSH_PSW,lib8085::OpcodeData {"PUSH_PSW", InstructionSet::NOP, 0, 	1 } },
        { lib8085::InstructionSet::RAL,    lib8085::OpcodeData { "RAL", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RAR,    lib8085::OpcodeData { "RAR", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RC,     lib8085::OpcodeData { "RC", InstructionSet::NOP,	    0, 	1 } },
        { lib8085::InstructionSet::RET,    lib8085::OpcodeData { "RET", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RIM,    lib8085::OpcodeData { "RIM", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RLC,    lib8085::OpcodeData { "RLC", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RM,     lib8085::OpcodeData { "RM", 	 InstructionSet::NOP,   0, 	1 } },
        { lib8085::InstructionSet::RNC,    lib8085::OpcodeData { "RNC", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RNZ,    lib8085::OpcodeData { "RNZ", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RP,     lib8085::OpcodeData { "RP", InstructionSet::NOP, 	    0, 	1 } },
        { lib8085::InstructionSet::RPE,    lib8085::OpcodeData { "RPE", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RPO,    lib8085::OpcodeData { "RPO", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RRC,    lib8085::OpcodeData { "RRC", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::RST_0,  lib8085::OpcodeData { "RST_0", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_1,  lib8085::OpcodeData { "RST_1", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_2,  lib8085::OpcodeData { "RST_2", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_3,  lib8085::OpcodeData { "RST_3", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_4,  lib8085::OpcodeData { "RST_4", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_5,  lib8085::OpcodeData { "RST_5", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_6,  lib8085::OpcodeData { "RST_6", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RST_7,  lib8085::OpcodeData { "RST_7", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::RZ,     lib8085::OpcodeData { "RZ", InstructionSet::NOP, 	    0, 	1 } },
        { lib8085::InstructionSet::SBB_A,  lib8085::OpcodeData { "SBB_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_B,  lib8085::OpcodeData { "SBB_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_C,  lib8085::OpcodeData { "SBB_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_D,  lib8085::OpcodeData { "SBB_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_E,  lib8085::OpcodeData { "SBB_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_H,  lib8085::OpcodeData { "SBB_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_L,  lib8085::OpcodeData { "SBB_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBB_M,  lib8085::OpcodeData { "SBB_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SBI,    lib8085::OpcodeData { "SBI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::SHLD,   lib8085::OpcodeData { "SHLD", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::SIM,    lib8085::OpcodeData { "SIM", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SPHL,   lib8085::OpcodeData { "SPHL", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::STA,    lib8085::OpcodeData { "STA", InstructionSet::NOP, 	1, 	2 } },
        { lib8085::InstructionSet::STAX_B, lib8085::OpcodeData { "STAX_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::STAX_D, lib8085::OpcodeData { "STAX_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::STAX_H, lib8085::OpcodeData { "STAX_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::STC,    lib8085::OpcodeData { "STC", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_A,  lib8085::OpcodeData { "SUB_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_B,  lib8085::OpcodeData { "SUB_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_C,  lib8085::OpcodeData { "SUB_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_D,  lib8085::OpcodeData { "SUB_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_E,  lib8085::OpcodeData { "SUB_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_H,  lib8085::OpcodeData { "SUB_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_L,  lib8085::OpcodeData { "SUB_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUB_M,  lib8085::OpcodeData { "SUB_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::SUI,    lib8085::OpcodeData { "SUI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::XCHG,   lib8085::OpcodeData { "XCHG", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_A,  lib8085::OpcodeData { "XRA_A", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_B,  lib8085::OpcodeData { "XRA_B", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_C,  lib8085::OpcodeData { "XRA_C", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_D,  lib8085::OpcodeData { "XRA_D", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_E,  lib8085::OpcodeData { "XRA_E", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_H,  lib8085::OpcodeData { "XRA_H", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_L,  lib8085::OpcodeData { "XRA_L", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRA_M,  lib8085::OpcodeData { "XRA_M", InstructionSet::NOP, 	0, 	1 } },
        { lib8085::InstructionSet::XRI,    lib8085::OpcodeData { "XRI", InstructionSet::NOP, 	1, 	1 } },
        { lib8085::InstructionSet::XTHL,   lib8085::OpcodeData { "XTHL", InstructionSet::NOP, 	0, 	1 } }
    };

    return data;
}
